#!/usr/bin/expect
#!/bin/bash

# 解决终端显示异常的问题
#trap sigwinch spawned
trap {
    set rows [stty rows]
    set cols [stty columns]
    stty rows $rows columns $cols < $spawn_out(slave,name)
} WINCH

# 记录执行日志
#log_file /tmp/login.log

# 0-关闭日志/1-打开日志
#log_user 1

# 开启执行时调试
#exp_internal 1

#### 用户信息 ####
set user "anzhihe"
set pass "passwd"

# 选择中控机器
set relay "relay.chegva.com"
set machine [lindex $argv 0]

# 启动连接进程,-noecho 关闭spawn回显
spawn ssh  -o StrictHostKeyChecking=no -o LogLevel=quiet "$user@$relay"
set timeout 10

expect {
# 内部并行匹配    
#    "Googlekey shield code*" {
#        # 输入googlekey
#        expect_user -timeout -1 -re "(.*)\n"
#        set code $expect_out(1,string)
#        send "$code\n";
#        exp_continue;
#    }
#    "Password*" {
#        # 输入密码
#        send "$pass\n";
#        exp_continue;
#    }
#    "Option*"  {
#        # 选择中控
#        send "$relay\r";
#        exp_continue;
#    }
    "*$user\>" {
        # 连接线上机器
        send "$machine\r";
#        exp_continue;
    }
#    "*bash*" {
#        # 切换成root用户
#        sleep 0.3
#        send "sudo -iu root\r";
#    }
}

# 串行匹配,解决可能程序没准备好，却已经返回的情况
expect {
    "*bash*" {
        # 切换成root用户
        send "sudo -iu root\r";
    }
}

interact
